---
name: PerWorldInventory
version: 1.0.0
api: [1.0.0, 2.0.0, 3.0.0, 4.0.0, 5.0.0, 6.0.0, 7.0.0, 8.0.0]
main: BlockHorizons\PerWorldInventory\PerWorldInventory
author: BlockHorizons

commands:
  pwi:
    default: op
...
